# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - modules/domain/node_modules
            - modules/server/node_modules
            - modules/client/node_modules
          key: v3-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-
      - run: yarn test
  test-server:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-
      - run:
          command: |
            cd modules/domain
            yarn build
      - run: sudo yarn global add dredd@11.0.2
      - run:
          command: |
            cd modules/server
            yarn test

workflows:
  version: 2
  test-all:
    jobs:
      - build
      - test:
          requires:
            - build
      - test-server:
          requires:
            - build
