# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-
      - run: yarn
      - run: yarn workspace @januswel/domain rebuild
      - save_cache:
          paths:
            - node_modules
            - modules/domain/node_modules
            - modules/server/node_modules
            - modules/client/node_modules
            - modules/domain/dist
          key: v3-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-
      - run: yarn test
  test-server:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-
      - run: sudo yarn global add dredd@11.0.2
      - run: yarn workspace @januswel/server test
  test-e2e:
    docker:
      - image: circleci/node:10.15-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-
      - run: yarn start:server &
      - run: yarn start:client &
      - run: sleep 10
      - run: yarn workspace @januswel/client test:e2e
      - store_artifacts:
          path: modules/client/screenshots

workflows:
  version: 2
  test-all:
    jobs:
      - build
      - test:
          requires:
            - build
      - test-server:
          requires:
            - build
      - test-e2e:
          requires:
            - build
